AllCops:
  Exclude:
    - bin/bundle
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - users_app/db/**/*.rb
