version: "3.8"
services:
  users_app_postgres:
    image: postgres:14.2
    volumes:
      - users_app_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $USERS_APP_DB
    ports:
      - 5432

  users_app:
    image: ruby:3.1.2
    working_dir: /app
    depends_on:
      - users_app_postgres
    volumes:
      - ./users_app:/app
      - users_app_bundle:/usr/local/bundle
    environment:
      PGHOST: users_app_postgres
      PGPORT: 5432
      PGUSER: $PG_USER
      PGPASSWORD: $PG_PASSWORD
      PGDB: $USERS_APP_DB
    command: [bundle, exec, puma]
    ports:
      - 3001:3000
    stdin_open: true
    tty: true

  front:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./front:/app
      - front_node_modules:/app/node_modules
      - front_nuxt:/app/.nuxt
    command: [yarn, dev]
    ports:
      - 3000:3000
      - 24678:24678 # vite port

volumes:
  users_app_postgres:
  users_app_bundle:
  front_node_modules:
  front_nuxt:
